### ISSUE TITLE
我该怎么修改faveicon的颜色

### ISSUE THREAD

**Issue by dslcoding** [WilliamMaybe/FaveButton#1]
当用户点击查看并收藏信息的时候，变成选中颜色。如果当用户再次点击这条信息的时候，因为这条信息在用户的收藏列表里已经存在了，所以这个时候faveButton的颜色应该是选中的颜色。我该怎修改这个颜色。不知道您是否听懂了。而且self.collectBtn.normalColor = [UIColor redColor];这个修改不了颜色，是怎么回事

**Comment by dslcoding** [comment]
UIImage*image =[UIImage imageNamed:@"poemDetailHeart"];
        image = [image imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
        self.collectBtn.tintColor = MAINTHEMECOLOR;
        [self.collectBtn setBackgroundImage:image forState:UIControlStateNormal];
我的解决方法

**Comment by WilliamMaybe** [comment]
- (void)faveButton:(FaveButton *)faveButton didSelect:(BOOL)didSelect
{
    [faveButton setSelected:YES animated:NO];
}
在委托中可以这么做，我增加了新的方法

**Comment by dslcoding** [comment]
你可能还是没有明白我的意思，你给我的方法需要点击才能实现。我想要的效果是不点击，直接修改他的颜色。比如 你在微博上点击收藏一条信息。在次查看这条信息的时候，我要从数据库里查看你是不是已经收藏了，如果你已经收藏了，我就改变个颜色，如果没有我就正常。不改变颜色。

**Comment by WilliamMaybe** [comment]
那你就直接[faveButton setSelected:YES animated:NO];不是就可以了嘛
